"""store campus group information

Revision ID: 883625aacaf8
Revises: 312fd082b429
Create Date: 2022-09-04 11:34:47.297828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883625aacaf8'
down_revision = '312fd082b429'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus_groups',
    sa.Column('cg_group_name', sa.String(length=256), nullable=True),
    sa.Column('cg_group_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cg_group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campus_groups')
    # ### end Alembic commands ###
